export enum ActionsTypes {
    CHANGE_ORD_ST = 'CHANGE-ORD-ST',
    SET_ORD = 'SET-ORD',
    VIEW_ORD = 'VIEW-ORD',
    SET_CURRENT_PAGE = 'SET-CURRENT-PAGE',
    TOGLE_IS_FETCHING = 'TOGLE-IS-FETCHING',
    TOGLE_IS_STATUS_FETCHING = 'TOGLE_IS_STATUS_FETCHING',
    
    SET_ORDER = 'SET-ORDER',
    
    SET_SELLER_DATA = 'SET-SELLER-DATA',
    
    SET_SELLER_PROFILE = 'SET_SELLER_PROFILE',
    CHANGE_SELLER_DESCR = 'CHANGE_SELLER_DESCR',
}

